name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code from the repository
            - uses: actions/checkout@v4

            # Set up Node.js (version 20 as specified)
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Check style with ESLint
            - name: Check style
              run: npm run eslint

            # Build the app (make sure `dist` folder is generated)
            - name: Build the app
              run: npm run build

            # Start app in production mode (make sure it's ready to serve)
            - name: Start app in production mode
              run: npm run start-prod

            # Wait for the app to be ready
            - name: Wait for the server to be ready
              run: npx wait-on http://localhost:5000

            # Run e2e tests with Cypress
            - name: Run e2e tests with Cypress
              uses: cypress-io/github-action@v5
              with:
                  command: npm run test:e2e
                  start: npm run start-prod
                  wait-on: http://localhost:5000
